---
- name: Install MeiliSearch
  get_url:
    url: https://github.com/meilisearch/MeiliSearch/releases/download/v0.27.0/meilisearch-linux-amd64
    dest: /usr/local/bin/meilisearch
    mode: '0755'

- name: Create MeiliSearch service
  copy:
    dest: /etc/systemd/system/meilisearch.service
    content: |
      [Unit]
      Description=MeiliSearch
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/meilisearch --master-key={{ meilisearch_master_key }} --db-path /var/lib/meilisearch/data.ms
      Restart=always
      User=meilisearch
      Group=meilisearch
      LimitNOFILE=1048576

      [Install]
      WantedBy=multi-user.target
  notify:
    - start meilisearch

- name: Start and enable MeiliSearch
  systemd:
    name: meilisearch
    state: started
    enabled: yes
