services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: fpm
    container_name: sasin91-php-fpm
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - DATABASE_HOST=sasin91-database
      - DATABASE_USER=sasin91
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sasin91
      - WEBSOCKET_URL=ws://localhost:8080/ws
      - BASE_URL=http://localhost:8080/
    networks:
      - sasin91-network
    configs:
      - source: php-fpm-config
        target: /usr/local/etc/php-fpm.d/www.conf
      - source: php-config
        target: /usr/local/etc/php/conf.d/php.ini
  websocket:
    build:
      context: ./
      dockerfile: Dockerfile
      target: websocket
    container_name: sasin91-websocket
    ports:
      - "8085:8085"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/usr/bin/supervisord", "-c", "/etc/supervisor.d/websocket.conf"]
    environment:
      - PATH=/usr/bin:/usr/local/bin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8085
    configs:
      - source: supervisord-config
        target: /etc/supervisor/supervisord.conf
      - source: php-config
        target: /usr/local/etc/php/conf.d/php.ini
    networks:
      - sasin91-network

  nginx:
    image: nginx:latest
    container_name: sasin91-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - sasin91-network
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/app.conf

  database:
    image: mariadb:latest
    container_name: sasin91-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sasin91
      MYSQL_USER: sasin91
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - sasin91-network

  redis:
    image: redis:latest
    container_name: sasin91-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - sasin91-network

volumes:
  mariadb_data:
  redis_data:

networks:
  sasin91-network:

configs:
  php-config:
    file: ./docker/php.ini
  php-fpm-config:
    file: ./docker/php-fpm.conf
  nginx-config:
    file: ./docker/nginx.conf
  supervisord-config:
    file: ./docker/supervisord.conf
