---
- name: Install PHP and PHP-FPM
  dnf:
    name:
      - php
      - php-fpm
      - php-mbstring
      - php-pdo
      - php-mysqlnd
    state: present

- name: Configure PHP-FPM for Caddy
  copy:
    dest: /etc/php-fpm.d/www.conf
    content: |
      [www]
      user = caddy
      group = caddy
      listen = /run/php-fpm/www.sock
      listen.owner = caddy
      listen.group = caddy
      pm = dynamic
      pm.max_children = 50
      pm.start_servers = 10
      pm.min_spare_servers = 5
      pm.max_spare_servers = 15
      pm.max_requests = 500
  notify:
    - restart php-fpm

- name: Start and enable PHP-FPM service
  systemd:
    name: php-fpm
    state: started
    enabled: yes
