---
- hosts: all
  become: yes
  vars_files:
    - vault.yml
  
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

- hosts: web
  roles:
    - nginx
    - php-fpm
    - mariadb
    - deploy

- hosts: database
  roles:
    - mariadb

- hosts: cache
  roles: 
    - redis

- hosts: websocket
  roles:
    - websocket
    - icecast