---
- hosts: redis
  become: yes
  tasks:
    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Start Redis service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes

    # - name: Ensure Redis is listening on all interfaces
    #   ansible.builtin.lineinfile:
    #     path: /etc/redis.conf
    #     regexp: '^bind 127.0.0.1'
    #     line: 'bind 0.0.0.0'
    #     state: present

    - name: Restart Redis to apply changes
      ansible.builtin.systemd:
        name: redis
        state: restarted

